apiVersion: v1
kind: Pod
metadata:
  name: task2-db
  labels:
    app: task2-db
spec:
  containers:
  - name: task2-db
    image: pixcs13/task2-db:latest 
    ports: 
    - containerPort: 5000
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Maria
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: task2-db
spec:
  type: ClusterIP
  selector:
    app: task2-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 5000