apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app
    image: pixcs13/task2-app:latest 
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Maria
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000